### ISSUE TITLE
"HACS"

### ISSUE THREAD

**Issue by r3mcos3** [jnpetersen/lovelace-countdown-dates#1]
I've installed your plugin with the new "HACS" system but i get a error message 

`custom element doesn't exist countdown-dates `
before with custom updater it works but now it don't

**Comment by jnpetersen** [comment]
I'll check this out.  Thanks for letting me know.

**Comment by Schocker360** [comment]
Feature request:

I really like your plugin!!  Something that would be great as a feature would be sorting the list by days left.

Great job!
